repos:
  - repo: local
    hooks:
      - id: pytest-cov
        name: Run pytest + coverage
        entry: uv run pytest --cov=src/ --cov-branch --cov-fail-under=80 tests
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint
        entry: uv run pylint src/
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: bandit
        name: Run bandit security
        entry: uv run bandit -c pyproject.toml -r src/
        language: system
        pass_filenames: false
